/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_CpuInfo */

#ifndef _Included_util_CpuInfo
#define _Included_util_CpuInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_CpuInfo
 * Method:    asmGetCpuId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_util_CpuInfo_asmGetCpuId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
